### ISSUE TITLE
Biography Statement Required

### ISSUE THREAD

**Issue by antsoftsystems** [lepidus/toggleRequiredMetadata#2]
Olá Pessoal,
Mesmo depois de desabilitar a opção Biography Statement. Não estamos conseguindo editar o metadados dos autores, pois o campo Biography  continua marcado como requerido.

Hello Guys,
Even after disabling the Biography Statement option. We are unable to edit the authors' metadata, as the Biography field is still marked as required.

William Rodrigues
AntSoft Systems On Demand

**Comment by diegoabadan** [comment]
Olá William.
Qual a versão do OJS?

**Comment by antsoftsystems** [comment]
Diego
OJS 3.3.0-10

**Comment by diegoabadan** [comment]
Obrigado! A nossa equipe irá investigar o defeito relatado e em breve daremos retorno.

**Comment by diegoabadan** [comment]
Obrigado pelo aviso e pelas informações, William!
Estamos preparando uma correção.

**Comment by diegoabadan** [comment]
Plugin atualizado com a correção.
